
# --- local/hybrids                                             [.gitlab-ci.yml]
# [2024-02-13][13:20:00] 001 Kartonagnick    

variables:
  GIT_STRATEGY:           clone
  GIT_SUBMODULE_STRATEGY: recursive
  DIR_DEPLOY:             .\deploy\run
  DIR_ARTIFACT:           .\_artifacts

before_script:
  - 'echo off'
#  - 'call "%DIR_DEPLOY%\02-init.bat" "%DIR_ARTIFACT%"'

stages:
  - clean
  - build
  - test
  - deploy

inspect:
  stage: clean
  script:
    - 'echo cloning repository... success!'
#    - 'call "%DIR_DEPLOY%\03-clean.bat" artifact'
#    - 'call "%DIR_DEPLOY%\03-clean.bat" msvc2019:64:release:static'

build-msvc2019:
  stage: build
  variables:
    GIT_STRATEGY: none
  script:
#    - 'call "%DIR_DEPLOY%\04-build.bat" msvc2019:64:release:static'

test-msvc2019:
  stage: test
  variables:
    GIT_STRATEGY: none
  script:
#    - 'call "%DIR_DEPLOY%\05-test.bat" msvc2019:64:release:static'

deploy:
  stage: deploy
  variables:
    GIT_STRATEGY: none
#  only:
#  - master
  script:
    - 'echo [deploy] ...'
    - 'echo [uploading] to ftp server ...'
#    - 'call "%DIR_DEPLOY%\06-upload.bat"'
#    - 'call "%DIR_DEPLOY%\03-clean.bat" msvc2019:64:release:static'
  dependencies:
    - test-msvc2019
  artifacts:
#    untracked: true
    paths:
    - '%DIR_ARTIFACT%\*'
    when: on_success
    expire_in: 2 days
